const data = {
  products: [
    {
      _id: "1",
      name: "Amazon box",
      category: "Shirts",
      image: "/images/alexa.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
      location: "Prince Risborough - 20 miles away",
    },
    {
      _id: "2",
      name: "Adidas Fit mics",
      category: "Shirts",
      image: "/images/boatHeadFone.jpg",
      price: 100,
      countInStock: 20,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
      location: "Prince Risborough - 28 miles away",
    },
    {
      _id: "3",
      name: "Camera dslr cannon",
      category: "Shirts",
      image: "/images/camera.jpg",
      price: 220,
      countInStock: 0,
      brand: "Lacoste",
      rating: 4.8,
      numReviews: 17,
      description: "high quality product",
      location: "Prince Risborough - 26 miles away",
    },
    {
      _id: "4",
      name: "mobile phone",
      category: "Pants",
      image: "/images/micromaxinB.jpg",
      price: 78,
      countInStock: 15,
      brand: "Nike",
      rating: 4.5,
      numReviews: 14,
      description: "high quality product",
      location: "Prince Risborough - 7 mile away",
    },
    {
      _id: "5",
      name: "Google mouse",
      category: "Pants",
      image: "/images/mouse.jpg",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
      location: "Prince Risborough - 70 miles away",
    },
    {
      _id: "6",
      name: "game set for children",
      category: "Pants",
      image: "/images/playstation.jpg",
      price: 139,
      countInStock: 12,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 15,
      description: "high quality product",
      location: "Prince Risborough - 11 miles away",
    },
  ],
};
export default data;
